Download latest kubecolor and change evcc persistance data store

diff --git a/truenas/k3s-jail-config b/truenas/k3s-jail-config
--- a/truenas/k3s-jail-config
+++ b/truenas/k3s-jail-config
@@ -51,7 +51,49 @@ initial_setup=#!/usr/bin/bash
   INSTALL_K3S_CHANNEL=latest sh -s - server --cluster-init \
   --disable=servicelb,traefik \
   --kubelet-arg="allowed-unsafe-sysctls=net.ipv4.conf.*"
-  apt install kubecolor -y
+
+  # Install Kubecolor
+  # URL for the latest release page of kubecolor
+  LATEST_RELEASE_URL="https://github.com/kubecolor/kubecolor/releases/latest"
+
+  # Use curl to get the URL of the latest release quietly
+  REDIRECT_URL=$(curl -sL -o /dev/null -w %{url_effective} $LATEST_RELEASE_URL)
+
+  # Extract the tag (release version) from the URL
+  TAG=$(basename $REDIRECT_URL)
+
+  # Strip the leading 'v' from the tag
+  TAG=${TAG#v}
+
+  # Construct the download URL for the amd64 release
+
+  DOWNLOAD_URL="https://github.com/kubecolor/kubecolor/releases/download/v${TAG}/kubecolor_${TAG}_linux_amd64.tar.gz"
+  echo "Downloading from: ${DOWNLOAD_URL}"
+  # Download the release tarball quietly
+  curl -sL -o kubecolor_${TAG}_Linux_x86_64.tar.gz $DOWNLOAD_URL
+
+  # Verify the download
+  if [[ $? -eq 0 ]]; then
+      echo "Download completed successfully."
+  else
+      echo "Download failed."
+      exit 1
+  fi
+
+  # Extract the tarball quietly
+  tar -xzf kubecolor_${TAG}_Linux_x86_64.tar.gz -C .
+
+  # Verify extraction
+  if [[ $? -eq 0 ]]; then
+      echo "Extraction completed successfully."
+  else
+      echo "Extraction failed."
+      exit 1
+  fi
+
+  echo "kubecolor downloaded and extracted successfully."
+
+  cp kubecolor /usr/bin/kubecolor
 
   # Bootstrap Argo CD
   git clone https://github.com/javydekoning/homelab.git ~/homelab
